import Head from "next/head";
import { FaDiscord, FaTwitter, FaInstagram } from "react-icons/fa";
import { useTheme } from "next-themes";
import { SunIcon, MoonIcon } from "@heroicons/react/solid";
import styles from "../styles/Home.module.css";
import AutoPlay from "../components/Slider";
import Roadmap from "../components/Roadmap";
import Team from "../components/Team";
import { useEffect, useState } from "react";
import FAQ from "../components/FAQ";
import { Link } from "react-scroll";

export default function Home() {
  const [mounted, setMounted] = useState(false);
  const { systemTheme, theme, setTheme } = useTheme();

  useEffect(() => {
    setMounted(true);
  }, []);

  const renderThemeChanger = () => {
    const currentTheme = theme === "system" ? systemTheme : theme;

    if (currentTheme === "dark") {
      return (
        <SunIcon
          className="w-7 h-7"
          role="button"
          onClick={() => setTheme("light")}
        />
      );
    } else {
      return (
        <MoonIcon
          className="w-7 h-7"
          role="button"
          onClick={() => setTheme("dark")}
        />
      );
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>The Bohemian Boys</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div name="home" className={styles.navbar}>
        <h1>The Bohemian Boys</h1>
        <div>
          <ul>
            <li>
              <Link to="home" smooth={true} offset={0} duration={500}>
                Home
              </Link>
            </li>
            <li>
              <Link to="about" smooth={true} offset={0} duration={500}>
                About
              </Link>
            </li>
            <li>
              <Link to="roadmap" smooth={true} offset={0} duration={500}>
                Roadmap
              </Link>
            </li>
            <li>
              <Link to="team" smooth={true} offset={0} duration={500}>
                Team
              </Link>
            </li>
            <li>
              <Link to="faq" smooth={true} offset={0} duration={500}>
                FAQ
              </Link>
            </li>
          </ul>

          {renderThemeChanger()}
        </div>
      </div>

      <main className={styles.main}>
        <div className={styles.pagePadding}>
          <div className={styles.containerLarge}>
            <div className={styles.paddingXhuge}>
              <div className={styles.homeHeader_component}>
                <div className={styles.textAlignCenter}>
                  <div className={styles.maxWidthLarge}>
                    <div className={styles.marginSmall}>
                      <h1>
                        The project that inspired the modern Bohemian Boys
                      </h1>
                    </div>
                    <div className={styles.marginMedium}>
                      <div className={styles.maxWidthSmall}>
                        <p>
                          8090 unique collectible characters with proof of
                          ownership stored on the Ethereum blockchain.
                        </p>
                      </div>
                    </div>
                    <div className={styles.buttonWrapper}>
                      <a id="mint-button" href="#" className={styles.button}>
                        Mint now
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>

      <div style={{ marginBottom: 50 }}>
        <AutoPlay />
      </div>

      <Roadmap />

      <Team />

      <FAQ color={theme === "light" ? "black" : "white"} />

      <footer className={styles.footer}>
        <h1>The Bohemian Boys</h1>

        <div>
          <a href="#">
            <FaDiscord size={26} />
          </a>
          <a href="#">
            <FaTwitter size={26} />
          </a>
          <a href="#">
            <FaInstagram size={26} />
          </a>
        </div>
      </footer>
    </div>
  );
}
